# static_map - True if using existing map

global_costmap:
  global_frame: /map #change
  robot_base_frame: /chassis
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 0.05
  static_map: false
  width: 100.0 #change
  height: 100.0 #change
  origin_x: -50.0 #change
  origin_y: -50.0 #change
